server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/finance_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: israelenspy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      transaction: transactions

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: bW9yZV9zZWN1cmVfand0X3NlY3JldF9iYWVsX2Zvcl9lbmNvZGluZ19saW5l
  expirationMs: 86400000
