CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS event_db;
CREATE DATABASE IF NOT EXISTS finance_db;
CREATE DATABASE IF NOT EXISTS member_db;
CREATE DATABASE IF NOT EXISTS messaging_db;
